# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
   admin.article:
        class: ArticleBundle\Admin\ArticleAdmin
        arguments: [~, ArticleBundle\Entity\Article, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Article }
        public: true
   admin.news:
        class: FrontendBundle\Admin\NewsAdmin
        arguments: [~, FrontendBundle\Entity\News, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: News }
        public: true
   admin.team:
        class: FrontendBundle\Admin\TeamAdmin
        arguments: [~, FrontendBundle\Entity\Team, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Team }
        public: true