news_index:
    path:     /
    defaults: { _controller: "FrontendBundle:News:index" }
    methods:  GET

news_show:
    path:     /{id}/show
    defaults: { _controller: "FrontendBundle:News:show" }
    methods:  GET

news_new:
    path:     /new
    defaults: { _controller: "FrontendBundle:News:new" }
    methods:  [GET, POST]

news_edit:
    path:     /{id}/edit
    defaults: { _controller: "FrontendBundle:News:edit" }
    methods:  [GET, POST]

news_delete:
    path:     /{id}/delete
    defaults: { _controller: "FrontendBundle:News:delete" }
    methods:  DELETE
