team_index:
    path:     /
    defaults: { _controller: "FrontendBundle:Team:index" }
    methods:  GET

team_show:
    path:     /{id}/show
    defaults: { _controller: "FrontendBundle:Team:show" }
    methods:  GET
